Broken when attempting to load
template1=# CREATE FUNCTION pg_snap_old(text, integer) RETURNS integer AS 'pg_snap_old' LANGUAGE C;
ERROR:  incompatible library "/usr/lib/postgresql/9.4/lib/pg_snap_old.so": missing magic block
HINT:  Extension libraries are required to use the PG_MODULE_MAGIC macro.

The code *is* using the PG_MODULE_MAGIC macro. I only have one version
of postgres installed. When I use pg_config it tells me that it
references 9.4.4.

I have looked but cannot find a solution to this. :(